name: velocityestoque
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  provider: ^6.1.2
  web_socket_channel: ^3.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  mime: ^2.0.0
  file_selector: ^1.0.3
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  icons_launcher: ^3.0.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
    - lib/assets/velocitylogo2.png
    - lib/assets/.env.development
    - lib/assets/.env.production
    
scripts:
  dev: flutter run --dart-define=env=development
  prod: flutter run --dart-define=env=production